[profile.default]
solc_version = "0.8.18" ## versao um pouco mais antiga que o normal quando for inicializar o projeto no foundry
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
]
optimizer = true
optimezer_runs = 50
evm_version = "paris" ##importante colocar na versao mais antiga para funcionar o deploy


[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
bvm = "${NOSTEST_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
