[profile.default]
solc_version = "0.8.24"
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
]
optimizer = true
optimezer_runs = 50
evm_version = "cancun"


[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
nostest = "${NOSTEST_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
